parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: deploymentRegion
  type: string
  default: 'eastus'

stages:
  - stage: Deploy_to__${{ parameters.environmentName }}
    displayName: Deploy to ${{ parameters.environmentName }}
    jobs:
    - deployment: ${{ parameters.environmentName }}_Deployment
      displayName: ${{ parameters.environmentName }} Deployment
      pool:
        vmImage: ubuntu-latest
      environment: ${{ parameters.environmentName }}
      variables:
        infraTemplate: $(Pipeline.Workspace)/infrastructure/bicep/main.bicep
        parameterFile: $(Pipeline.Workspace)/infrastructure/bicep/parameters/main.${{ parameters.environmentName }}.json
        variableScriptFile: $(Pipeline.Workspace)/scripts/Set-PipelineVariablesFromDeploymentOutput.ps1
        functionPackage: $(Pipeline.Workspace)/functionapp/functionapp.zip
        setFunctionSecretScriptFile: $(Pipeline.Workspace)/scripts/set-function-key-secret.sh
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: Download Infrastructure Artifact
              inputs:
                artifact: 'infrastructure'
            
            - task: DownloadPipelineArtifact@2
              displayName: Download Pipeline Scritps Artifact
              inputs:
                artifact: scripts
            
            - task: DownloadPipelineArtifact@2
              displayName: Download Function App Artifact
              inputs:
                artifact: functionapp
            
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy Infrastructure to ${{ parameters.environmentName }}
              inputs:
                deploymentScope: Resource Group
                azureResourceManagerConnection: ${{ parameters.serviceConnectionName }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                csmFile: $(infraTemplate)
                csmParametersFile: $(parameterFile)
                deploymentName: $(Build.BuildId)
                overrideParameters: '-buildId $(Build.BuildId)'
                location: ${{ parameters.deploymentRegion }}
                deploymentOutputs: infraOutputs
            
            - task: PowerShell@2
              displayName: Set Variables from Deployment Output
              inputs:
                filePath: $(variableScriptFile)
                arguments: -armOutputString '$(infraOutputs)'
            
            - task: AzureFunctionApp@1
              displayName: Deploy Order Fulfillment Function App
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                appType: functionAppLinux
                appName: $(functionAppName)
                package: $(functionPackage)

            - task: AzureCLI@2
              displayName: Set Function App Key
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                scriptPath: $(setFunctionSecretScriptFile)
                scriptType: bash
                scriptLocation: scriptPath
                arguments: ${{ parameters.resourceGroupName }} $(functionAppName) $(keyVaultName)
            
            - task: AzureCLI@2
              displayName: Import Product Ordering OpenAPI Spec into APIM
              inputs:
                azureSubscription: ${{ parameters.serviceConnectionName }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  API_VERSION="2024-01-02"
                  OPENAPI_URL="https://$(functionAppHostName)/api/swagger.json"
                  az apim api import \
                    --path /productordering \
                    --resource-group ${{ parameters.resourceGroupName }} \
                    --service-name $(apimName) \
                    --api-id productordering \
                    --display-name "Product Ordering" \
                    --api-type http \
                    --specification-format OpenApi \
                    --specification-url $(Pipeline.Workspace)/productordering/openapi.json \
                    --api-version $API_VERSION
